GET http://warm-forest-14168.herokuapp.com/users/

###

GET http://warm-forest-14168.herokuapp.com/users/initialUser@email.com

###

POST http://warm-forest-14168.herokuapp.com/auth/register
Content-Type: application/json

{
    "email": "testUser2@email.com",
    "password": "Test Password",
    "userName": "Test User 4"
}

###

POST http://warm-forest-14168.herokuapp.com/auth/login
Content-Type: application/json

{
    "email": "initialUser@email.com",
    "password": "Test Password"
}

###

POST http://warm-forest-14168.herokuapp.com/auth/token
Content-Type: application/json

{
    "email": "initialUser@email.com",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJpbml0aWFsVXNlckBlbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkluaXRpYWwgVXNlciIsImlhdCI6MTYzOTUwNDE2Nn0.HJRQ2AQrJ9qk9Huf9FZaixUjpeYGziS07xzEPk4VpF4"
}

###

POST http://warm-forest-14168.herokuapp.com/auth/logout
Content-Type: application/json

{
    "email": "initialUser@email.com",
    "token": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJpbml0aWFsVXNlckBlbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkluaXRpYWwgVXNlciIsImlhdCI6MTYzOTUwNDcwN30.zTASHCGode_memp_9dLOxw-BMPcEgS7GikJYditFTxE"
}

###

GET http://warm-forest-14168.herokuapp.com/initialUser@email.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJpbml0aWFsVXNlckBlbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkluaXRpYWwgVXNlciIsImlhdCI6MTYzOTU4MDQ1MiwiZXhwIjoxNjM5NTgxNjUyfQ.Pv_Tb0MIpdQqKATata7496QkxzcaCaJb6HH61Dpv974

###

GET http://warm-forest-14168.herokuapp.com/leaderboard/Water
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJpbml0aWFsVXNlckBlbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkluaXRpYWwgVXNlciIsImlhdCI6MTYzOTU2NDUwMCwiZXhwIjoxNjM5NTY1NzAwfQ.GbcV7nhhHVMA9o_sfGQl4494sXxseZ56ZwM_y52vSXg

###

POST http://warm-forest-14168.herokuapp.com/habits/initialUser@email.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJpbml0aWFsVXNlckBlbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkluaXRpYWwgVXNlciIsImlhdCI6MTYzOTU4MTcyOCwiZXhwIjoxNjM5NTgyOTI4fQ.7O86kcldsQ9XfbC3XGYmyDDd_xPoo_jyRTXl_yhdJBc

{
    "userName": "Initial User",
    "habitName": "never",
    "frequency": 1,
    "unit": "boolean"
}

###

DELETE http://warm-forest-14168.herokuapp.com/habits/61ba08a96bd5650eb9731787
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJpbml0aWFsVXNlckBlbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkluaXRpYWwgVXNlciIsImlhdCI6MTYzOTU4MTcyOCwiZXhwIjoxNjM5NTgyOTI4fQ.7O86kcldsQ9XfbC3XGYmyDDd_xPoo_jyRTXl_yhdJBc