GET http://warm-forest-14168.herokuapp.com/users/

###

GET http://warm-forest-14168.herokuapp.com/users/initialUser@email.com

###

POST http://warm-forest-14168.herokuapp.com/auth/register
Content-Type: application/json

{
    "email": "initialUser1@email.com",
    "password": "Test Password",
    "userName": "Initial User"
}

###

POST http://warm-forest-14168.herokuapp.com/auth/login
Content-Type: application/json

{
    "email": "initialUser@email.com",
    "password": "Test Password"
}

###

POST http://warm-forest-14168.herokuapp.com/auth/token
Content-Type: application/json

{
    "email": "initialUser@email.com",
    "token": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJpbml0aWFsVXNlckBlbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkluaXRpYWwgVXNlciIsImlhdCI6MTYzOTYxMzkxMH0.CDW48Gniyw0uBhMbGLvXXpx-dBmA4bOt8PK4KuRRoCQ"
}

###

POST http://warm-forest-14168.herokuapp.com/auth/logout
Content-Type: application/json

{
    "email": "initialUser@email.com",
    "token": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJpbml0aWFsVXNlckBlbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkluaXRpYWwgVXNlciIsImlhdCI6MTYzOTYxNDAwOH0.OWA-H5rbGrFZiDS4Dse9fJEmQJ3KA3LfXCWtRm5NoOU"
}

###

GET http://warm-forest-14168.herokuapp.com/habits/initialUser@email.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJpbml0aWFsVXNlckBlbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkluaXRpYWwgVXNlciIsImlhdCI6MTYzOTYxNDAwOCwiZXhwIjoxNjM5NjE1MjA4fQ.mTVjZkHyav9fgbDPyFh9WtQcRTc2u0I0YlpPl0tIOMw

###

GET http://warm-forest-14168.herokuapp.com/habits/leaderboard/Water
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJpbml0aWFsVXNlckBlbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkluaXRpYWwgVXNlciIsImlhdCI6MTYzOTYxNDAwOCwiZXhwIjoxNjM5NjE1MjA4fQ.mTVjZkHyav9fgbDPyFh9WtQcRTc2u0I0YlpPl0tIOMw

###

POST http://warm-forest-14168.herokuapp.com/habits/initialUser@email.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJpbml0aWFsVXNlckBlbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkluaXRpYWwgVXNlciIsImlhdCI6MTYzOTYxNDAwOCwiZXhwIjoxNjM5NjE1MjA4fQ.mTVjZkHyav9fgbDPyFh9WtQcRTc2u0I0YlpPl0tIOMw

{
    "userName": "Initial User",
    "habitName": "never",
    "frequency": 1,
    "unit": "boolean"
}

###

DELETE http://warm-forest-14168.herokuapp.com/habits/61ba865c16f11bf42bca78b7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJpbml0aWFsVXNlckBlbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkluaXRpYWwgVXNlciIsImlhdCI6MTYzOTYxNDAwOCwiZXhwIjoxNjM5NjE1MjA4fQ.mTVjZkHyav9fgbDPyFh9WtQcRTc2u0I0YlpPl0tIOMw